manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: royyandzakiy
      url-base: https://github.com/royyandzakiy
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  projects:
    - name: sdk-nrf
      remote: nrfconnect
      revision: v3.2.1
      import:
        name-allowlist:
          - sdk-zephyr
          - sdk-nrfxlib
          - mcuboot
          - mbedtls
          - trusted-firmware-m
          - cmsis
          - hal-nordic
      path: ncs

    - name: balancer-robot-firmware
      remote: royyandzakiy
      revision: main
      path: firmware   # Folder name in your local workspace

    - name: balancer-robot-app
      remote: royyandzakiy
      revision: main
      path: desktop-app # Folder name in your local workspace

  self:
    path: workspace-manifest